/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as PartenaireRouteImport } from './routes/partenaire'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitsIndexRouteImport } from './routes/produits.index'
import { Route as PartenaireIndexRouteImport } from './routes/partenaire.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProduitsIdRouteImport } from './routes/produits.$id'
import { Route as PartenaireProduitsRouteImport } from './routes/partenaire.produits'
import { Route as PartenaireParametresRouteImport } from './routes/partenaire.parametres'
import { Route as PartenaireConnexionRouteImport } from './routes/partenaire.connexion'
import { Route as PartenaireCommandesRouteImport } from './routes/partenaire.commandes'
import { Route as AdminStatistiquesRouteImport } from './routes/admin.statistiques'
import { Route as AdminFournisseursRouteImport } from './routes/admin.fournisseurs'
import { Route as AdminCommandesRouteImport } from './routes/admin.commandes'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as PartenaireProduitsNouveauRouteImport } from './routes/partenaire.produits.nouveau'

const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenaireRoute = PartenaireRouteImport.update({
  id: '/partenaire',
  path: '/partenaire',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProduitsRoute,
} as any)
const PartenaireIndexRoute = PartenaireIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartenaireRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProduitsIdRoute = ProduitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProduitsRoute,
} as any)
const PartenaireProduitsRoute = PartenaireProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => PartenaireRoute,
} as any)
const PartenaireParametresRoute = PartenaireParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => PartenaireRoute,
} as any)
const PartenaireConnexionRoute = PartenaireConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => PartenaireRoute,
} as any)
const PartenaireCommandesRoute = PartenaireCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => PartenaireRoute,
} as any)
const AdminStatistiquesRoute = AdminStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFournisseursRoute = AdminFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const PartenaireProduitsNouveauRoute =
  PartenaireProduitsNouveauRouteImport.update({
    id: '/nouveau',
    path: '/nouveau',
    getParentRoute: () => PartenaireProduitsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/commande': typeof CommandeRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confirmation': typeof ConfirmationRoute
  '/panier': typeof PanierRoute
  '/partenaire': typeof PartenaireRouteWithChildren
  '/produits': typeof ProduitsRouteWithChildren
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/fournisseurs': typeof AdminFournisseursRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/partenaire/commandes': typeof PartenaireCommandesRoute
  '/partenaire/connexion': typeof PartenaireConnexionRoute
  '/partenaire/parametres': typeof PartenaireParametresRoute
  '/partenaire/produits': typeof PartenaireProduitsRouteWithChildren
  '/produits/$id': typeof ProduitsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/partenaire/': typeof PartenaireIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/partenaire/produits/nouveau': typeof PartenaireProduitsNouveauRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/commande': typeof CommandeRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confirmation': typeof ConfirmationRoute
  '/panier': typeof PanierRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/fournisseurs': typeof AdminFournisseursRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/partenaire/commandes': typeof PartenaireCommandesRoute
  '/partenaire/connexion': typeof PartenaireConnexionRoute
  '/partenaire/parametres': typeof PartenaireParametresRoute
  '/partenaire/produits': typeof PartenaireProduitsRouteWithChildren
  '/produits/$id': typeof ProduitsIdRoute
  '/admin': typeof AdminIndexRoute
  '/partenaire': typeof PartenaireIndexRoute
  '/produits': typeof ProduitsIndexRoute
  '/partenaire/produits/nouveau': typeof PartenaireProduitsNouveauRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/commande': typeof CommandeRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confirmation': typeof ConfirmationRoute
  '/panier': typeof PanierRoute
  '/partenaire': typeof PartenaireRouteWithChildren
  '/produits': typeof ProduitsRouteWithChildren
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/fournisseurs': typeof AdminFournisseursRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/partenaire/commandes': typeof PartenaireCommandesRoute
  '/partenaire/connexion': typeof PartenaireConnexionRoute
  '/partenaire/parametres': typeof PartenaireParametresRoute
  '/partenaire/produits': typeof PartenaireProduitsRouteWithChildren
  '/produits/$id': typeof ProduitsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/partenaire/': typeof PartenaireIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/partenaire/produits/nouveau': typeof PartenaireProduitsNouveauRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/commande'
    | '/comment-ca-marche'
    | '/confirmation'
    | '/panier'
    | '/partenaire'
    | '/produits'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/fournisseurs'
    | '/admin/statistiques'
    | '/partenaire/commandes'
    | '/partenaire/connexion'
    | '/partenaire/parametres'
    | '/partenaire/produits'
    | '/produits/$id'
    | '/admin/'
    | '/partenaire/'
    | '/produits/'
    | '/partenaire/produits/nouveau'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/commande'
    | '/comment-ca-marche'
    | '/confirmation'
    | '/panier'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/fournisseurs'
    | '/admin/statistiques'
    | '/partenaire/commandes'
    | '/partenaire/connexion'
    | '/partenaire/parametres'
    | '/partenaire/produits'
    | '/produits/$id'
    | '/admin'
    | '/partenaire'
    | '/produits'
    | '/partenaire/produits/nouveau'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/commande'
    | '/comment-ca-marche'
    | '/confirmation'
    | '/panier'
    | '/partenaire'
    | '/produits'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/fournisseurs'
    | '/admin/statistiques'
    | '/partenaire/commandes'
    | '/partenaire/connexion'
    | '/partenaire/parametres'
    | '/partenaire/produits'
    | '/produits/$id'
    | '/admin/'
    | '/partenaire/'
    | '/produits/'
    | '/partenaire/produits/nouveau'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommandeRoute: typeof CommandeRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ConfirmationRoute: typeof ConfirmationRoute
  PanierRoute: typeof PanierRoute
  PartenaireRoute: typeof PartenaireRouteWithChildren
  ProduitsRoute: typeof ProduitsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaire': {
      id: '/partenaire'
      path: '/partenaire'
      fullPath: '/partenaire'
      preLoaderRoute: typeof PartenaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/': {
      id: '/produits/'
      path: '/'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/partenaire/': {
      id: '/partenaire/'
      path: '/'
      fullPath: '/partenaire/'
      preLoaderRoute: typeof PartenaireIndexRouteImport
      parentRoute: typeof PartenaireRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produits/$id': {
      id: '/produits/$id'
      path: '/$id'
      fullPath: '/produits/$id'
      preLoaderRoute: typeof ProduitsIdRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/partenaire/produits': {
      id: '/partenaire/produits'
      path: '/produits'
      fullPath: '/partenaire/produits'
      preLoaderRoute: typeof PartenaireProduitsRouteImport
      parentRoute: typeof PartenaireRoute
    }
    '/partenaire/parametres': {
      id: '/partenaire/parametres'
      path: '/parametres'
      fullPath: '/partenaire/parametres'
      preLoaderRoute: typeof PartenaireParametresRouteImport
      parentRoute: typeof PartenaireRoute
    }
    '/partenaire/connexion': {
      id: '/partenaire/connexion'
      path: '/connexion'
      fullPath: '/partenaire/connexion'
      preLoaderRoute: typeof PartenaireConnexionRouteImport
      parentRoute: typeof PartenaireRoute
    }
    '/partenaire/commandes': {
      id: '/partenaire/commandes'
      path: '/commandes'
      fullPath: '/partenaire/commandes'
      preLoaderRoute: typeof PartenaireCommandesRouteImport
      parentRoute: typeof PartenaireRoute
    }
    '/admin/statistiques': {
      id: '/admin/statistiques'
      path: '/statistiques'
      fullPath: '/admin/statistiques'
      preLoaderRoute: typeof AdminStatistiquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fournisseurs': {
      id: '/admin/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/admin/fournisseurs'
      preLoaderRoute: typeof AdminFournisseursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/partenaire/produits/nouveau': {
      id: '/partenaire/produits/nouveau'
      path: '/nouveau'
      fullPath: '/partenaire/produits/nouveau'
      preLoaderRoute: typeof PartenaireProduitsNouveauRouteImport
      parentRoute: typeof PartenaireProduitsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminFournisseursRoute: typeof AdminFournisseursRoute
  AdminStatistiquesRoute: typeof AdminStatistiquesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminFournisseursRoute: AdminFournisseursRoute,
  AdminStatistiquesRoute: AdminStatistiquesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PartenaireProduitsRouteChildren {
  PartenaireProduitsNouveauRoute: typeof PartenaireProduitsNouveauRoute
}

const PartenaireProduitsRouteChildren: PartenaireProduitsRouteChildren = {
  PartenaireProduitsNouveauRoute: PartenaireProduitsNouveauRoute,
}

const PartenaireProduitsRouteWithChildren =
  PartenaireProduitsRoute._addFileChildren(PartenaireProduitsRouteChildren)

interface PartenaireRouteChildren {
  PartenaireCommandesRoute: typeof PartenaireCommandesRoute
  PartenaireConnexionRoute: typeof PartenaireConnexionRoute
  PartenaireParametresRoute: typeof PartenaireParametresRoute
  PartenaireProduitsRoute: typeof PartenaireProduitsRouteWithChildren
  PartenaireIndexRoute: typeof PartenaireIndexRoute
}

const PartenaireRouteChildren: PartenaireRouteChildren = {
  PartenaireCommandesRoute: PartenaireCommandesRoute,
  PartenaireConnexionRoute: PartenaireConnexionRoute,
  PartenaireParametresRoute: PartenaireParametresRoute,
  PartenaireProduitsRoute: PartenaireProduitsRouteWithChildren,
  PartenaireIndexRoute: PartenaireIndexRoute,
}

const PartenaireRouteWithChildren = PartenaireRoute._addFileChildren(
  PartenaireRouteChildren,
)

interface ProduitsRouteChildren {
  ProduitsIdRoute: typeof ProduitsIdRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
}

const ProduitsRouteChildren: ProduitsRouteChildren = {
  ProduitsIdRoute: ProduitsIdRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
}

const ProduitsRouteWithChildren = ProduitsRoute._addFileChildren(
  ProduitsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRouteWithChildren,
  CommandeRoute: CommandeRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ConfirmationRoute: ConfirmationRoute,
  PanierRoute: PanierRoute,
  PartenaireRoute: PartenaireRouteWithChildren,
  ProduitsRoute: ProduitsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
